# -*- coding: utf-8 -*-
"""Kode Program Deteksi Mobil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bp-X8mO7kK6woH1Zko7JjZfbmMD-72px
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2

# Capture video from file path
cap = cv2.VideoCapture('/content/carssss.mp4')

# Load pre-trained car classifier
car_cascade = cv2.CascadeClassifier('/content/haarcascade_cars.xml')

frame_counter = 0

# Read video frames until the video is completed
while True:
    ret, frame = cap.read()

    if not ret:
        break

    # Resize frame to reduce processing load (optional)
    frame = cv2.resize(frame, (640, 480))  # Resize to 640x480 pixels

    # Increment frame counter
    frame_counter += 1

    # Process every 10th frame to save resources
    if frame_counter % 10 == 0:
        # Convert frame to grayscale
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Detect cars in the frame
        cars = car_cascade.detectMultiScale(gray, 1.1, 3)

        # Draw rectangle around detected cars
        for (x, y, w, h) in cars:
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # Show the frame with detected cars
        cv2_imshow(frame)

    # Optional: Release frame memory after use (if necessary)
    frame = None

# Release the video capture object and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load pre-trained car classifier
car_cascade = cv2.CascadeClassifier('/content/haarcascade_cars.xml')

# Capture video
cap = cv2.VideoCapture('/content/carssss.mp4')

# Set up video parameters
frame_rate = cap.get(cv2.CAP_PROP_FPS)  # Get the frame rate (frames per second)
frame_counter = 0
previous_position = None
speed_kmh = 0  # Initialize speed_kmh to 0

# Define calibration (in meters per pixel)
meters_per_pixel = 15 / 200  # Adjust based on the actual size of the car in the video

# Function to calculate distance between two points (Euclidean distance)
def calculate_distance(point1, point2):
    return np.sqrt((point2[0] - point1[0])**2 + (point2[1] - point1[1])**2)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_counter += 1

    # Resize the frame to reduce the size of the analysis (resize to 320x240 to reduce memory usage)
    frame = cv2.resize(frame, (320, 240))  # Resize to smaller resolution

    # Convert frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect cars in the frame
    cars = car_cascade.detectMultiScale(gray, 1.1, 3)

    # If cars are detected, calculate position and speed
    for (x, y, w, h) in cars:
        # Calculate the center of the car's bounding box
        car_center = (x + w // 2, y + h // 2)

        # If this is not the first frame with a car, calculate speed
        if previous_position is not None:
            # Calculate the distance between the current and previous position
            distance = calculate_distance(previous_position, car_center)

            # Calculate speed in pixels per second
            speed_pixels_per_sec = distance * frame_rate  # Speed in pixels per second

            # Convert to meters per second, then km/h
            speed_meters_per_sec = speed_pixels_per_sec * meters_per_pixel  # Convert to meters per second
            speed_kmh = speed_meters_per_sec * 3.6  # Convert to kilometers per hour

        # Draw rectangle and speed info
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.putText(frame, f"Speed: {speed_kmh:.2f} km/h", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # Update previous position
        previous_position = car_center

    # Show the frame with speed information (only show every 10th frame)
    if frame_counter % 10 == 0:
        cv2_imshow(frame)  # Only show every 10th frame to save resources

    # Optional: Press Q to exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# Release video capture and close windows
cap.release()
cv2.destroyAllWindows()